### ISSUE TITLE
Final checklist

### ISSUE THREAD

**Issue by bsamseth** [bsamseth/thesis#34]
Things to look through before handing in. List meant to be exapanded on a running basis, not to be gone through before _everything_ else is completed.

- [x] All results have a clear link to the full source code.
- [x] Tables
  - [x] Captions above table
  - [x] All units clearly given
  - [x] Referenced in the text
  - [x] List of tables
- [x] Figures
  - [x] Captions below figure
  - [x] All axis labeled
  - [x] Legends where needed
  - [x] Referenced in text
  - [x] List of figures
- [x] Bibliography
  - [x] Entries use consistent format
  - [x] Decide on reference format (numeric or alphabetic)
- [x] Abbreviations list
  - [x] Consistent use of abbreviations
  - [x] Consistent use of capitalization of terms
- [ ] Notation consitency
  - [x] Check that \mat X is defined properly everywhere
  - [x] Consistent use of \psi, \Psi, \phi etc.
  - [x] Consider changing notation of Hamiltonians (\hat might be to small)
  - [x] Update notaion reference with everything
  - [x] All numbers formatted with \num or \SI
  - [x] Punctuation in all equations
- [ ] Spell checks
  - [x] Words
  - [x] Sentence build up
  - [x] Run check for passive voice, fill words etc.
  - [x] Decide on a spelling for hyper(-)parameters
  - [ ] Fix McMillian -> McMillan
